# SQLite version 3.x
#   gem install sqlite3
development:
  adapter: postgresql
  encoding: unicode
  database: stuinfo_development
  pool: 5
  username: postgres
  password: pmqpmq55

production:
  adapter: mysql2
  encoding: utf8
  reconnect: false
  database: stuinfo
  pool: 5
  username: root
  password: pmqpmq3577530
  host: localhost
